version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: bf-mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_vl:/val/lib/mysql

  redis:
    image: redis:latest
    container_name: bf-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_vl:/vla/lib/redis

volumes:
  mysql_vl:
    driver: local
  redis_vl:
    driver: local
