version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: bf-mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_vl:/val/lib/mysql

volumes:
  mysql_vl:
    driver: local
