spring:
  application:
    name: brandFinder

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator-mappings: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jwt:
    secretkey: ${JWT_KEY}
